### ISSUE TITLE
How to pass global variable

### ISSUE THREAD

**Issue by linonetwo** [mattblackdev/react-entity-component-system#1]
Hi, great package, works very well with react-pixi-fiber.

I have a question: How to pass a variable to inform all renderer that we are in DEBUG mode? So I can enable bounding box drawing.

Can I access other entities from a react function's props? In this way, I think I can set DEBUG in a World Entity, and every react function is checking that entity, to know whether we are in DEBUG mode.

But I don't know whether that will introduce performance issue.

**Comment by mattblackdev** [comment]
Thanks! I'd reach for React Context. 

CodeSandbox Example: https://codesandbox.io/s/useecs-react-context-example-0i0vh

**Comment by linonetwo** [comment]
I got it. This means I can even use Redux to manage the debug state and pass "connected component" to all entity's Render property.
