### ISSUE TITLE
Return raw entities in useEntityComponentSystem

### ISSUE THREAD

**Issue by linonetwo** [mattblackdev/react-entity-component-system#3]
I want to render something in the HUD (which is in HTML), instead of in the game (in react-pixi-fiber), so I need to get data from some entity.

I have to do so:

```js
const [entities, updater] = useEntityComponentSystem(
    initialEntities,
    systems,
  );

const data = filterHUDEntities(entities);
```

where

```
function filterHUDEntities(entities: Element<any>[]): Object[] {
  const filter = ['underMouse'];
  return entities
    .filter(entity => entity.props.name in filter)
    .map(entity => entity.props);
}
```

I have to restore entity data from  `entity.props`, which is verbose...

**Comment by mattblackdev** [comment]
Hey @linonetwo loving your interest in the package. I need to update the readme with this stuff, so thanks for asking these questions. There are currently 2 options to tap into the raw entities map:
#### Pass a renderer function (Probably not what you need):
```js
useEntityComponentSystem(
  initialEntities, 
  systems, 
  { renderEntities: (rawEntitiesMap) => doSomethingWithEntitiesButStillReturnJSX(rawEntitiesMap) }
)
```
This is provided to override the rendering and/or prop drilling, which you're not doing. If you're curious you could check out the [defaultRenderEntities function](https://github.com/mattblackdev/react-entity-component-system/blob/c00cd348967ac2638360a79386779b26ce8f58b2/src/helpers/defaultRenderEntities.jsx#L3).

But, I recommend the next way:

#### The third element returned from useECS is the raw entities map:
```js
const [renderedEntities, updater, rawEntitiesMap] = useEntityComponentSystem(initialEntities, systems)
const data = filterHUDEntities(Object.values(rawEntitiesMap))
```
Check this out for an example: https://codesandbox.io/s/useecs-raw-entities-example-igouv. The stock Debug component could use some filtering UI 😉

**Comment by linonetwo** [comment]
Thank you, that solves my problem ~
